CreatBankImage: CreatBankImage.c targa_image.o
	gcc -g CreatBankImage.c targa_image.o -o CreatBankImage

targa_image.o: targa_image.c
	gcc -g -c targa_image.c -o targa_image.o

clean:
	rm *.o, CreatBankImage
